version: 0.0
os: linux
files:
    - source: .
      destination: /home/ec2-user/
hooks:
    ApplicationStart:
        - location: ../../../../../../home/ec2-user/start.sh
          timeout: 300
          runas: ec2-user
    ApplicationStop:
        - location: ../../../../../../home/ec2-user/stop.sh
          timeout: 300
          runas: ec2-user


