version: 0.0
os: linux
files:
    - source: .
      destination: .
hooks:
    ApplicationStart:
        - location: ./start.sh
          timeout: 300
          runas: ec2-user
    ApplicationStop:
        - location: ./stop.sh
          timeout: 300
          runas: ec2-user


